config/routes.rb
Rails.application.routes.draw do

  mount Soulmate::Server, :at => "/autocomplete"
  resources :guests #, only: [:edit, :update] 

  get 'xyx' => 'sessions#new'
  root 'static_pages#index'
  get 'success'  => 'static_pages#success'
  get 'already_completed'  => 'static_pages#already_completed'
  get 'search'  => 'guests#search'

  
  resources :sessions, only: :index
  get "/auth/:provider/callback" => 'sessions#create'

end

app/models/guest.rb
require "rubygems"
require "google/api_client"
require "google_drive"

class Guest < ActiveRecord::Base
  after_save :load_into_soulmate
  before_destroy :remove_from_soulmate


  # It returns the articles whose titles contain one or more words that form the query
  def self.search(query)
    # where(:title, query) -> This would return an exact match of the query
    where("lower(name) like lower(?)", "%#{query}%").first
  end
    
  def send_activation_email
    GuestMailer.rsvp_confirmation(self).deliver_now
  end  
    
  def group
    Guest.where("household_id = ?", household_id)
  end

  def plusone?
    return false if plusone.nil?
  end

  def feed
    Guest.where("household_id = ?", @household_id)
  end
  
  
  
  def update_spreadsheet
    access_token = ::Token.last.fresh_token
    connection = ::GoogleDrive.login_with_oauth(access_token)
    ss = connection.spreadsheet_by_title('RSVPs')
    if ss.nil?
      ss = connection.create_spreadsheet('RSVPs')
    end
    ws = ss.worksheets[0]
    last_row = 1 + ws.num_rows
    ws.update_cells(last_row, 1, [[id,name,attending,notes,plusone,self.plusone_attending,
                       plusone_notes,email,household_id,updated_at]])
    ws.save
  end
  

  private

  def load_into_soulmate
    loader = Soulmate::Loader.new("guests")
    loader.add("term" => name,
    "id" => self.id,
    "data" => {
      "link" => Rails.application.routes.url_helpers.edit_guest_path(self)
    })
  end

  def remove_from_soulmate
    loader = Soulmate::Loader.new("guests")
    loader.remove("id" => self.id)
  end
end

app/models/token.rb
require 'net/http'
require 'json'
 
class Token < ActiveRecord::Base
 
  def to_params
    {'refresh_token' => refresh_token,
    'client_id' => ENV['CLIENT_ID'],
    'client_secret' => ENV['CLIENT_SECRET'],
    'grant_type' => 'refresh_token'}
  end
 
  def request_token_from_google
    url = URI("https://accounts.google.com/o/oauth2/token")
    Net::HTTP.post_form(url, self.to_params)
  end
 
  def refresh!
    response = request_token_from_google
    data = JSON.parse(response.body)
    update_attributes(
    access_token: data['access_token'],
    expires_at: Time.now + (data['expires_in'].to_i).seconds)
  end
 
  def expired?
    expires_at < Time.now
  end
 
  def fresh_token
    refresh! if expired?
    access_token
  end
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  before_action :set_guest, only: [:show, :edit, :update, :destroy]
  skip_before_filter :verify_authenticity_token, only: [:edit, :update]
  def index
    @guests = Guest.all
  end

  def search

  end

  def show
  end

  def new
    @guest = Guest.new
  end

  def edit
    @household_id = @guest.household_id
    @guests = Guest.where("household_id = ? AND NOT id = ?", @household_id, @guest)
    @groupcount = @guests.count+1
    @feed = @guest.feed

    if @guest.completed?
      redirect_to "/already_completed"
    end
  end

  def update
    @guest = Guest.find(params[:id])
    @guestorig = Guest.find(params[:id])
    @household_id = @guest.household_id
    @guests = Guest.where("household_id = ? AND NOT id = ?", @household_id, @guest)
    @groupcount = @guests.count+1
    
    if @groupcount == 1
      @guest.update_attributes(guest_params)
      UpdateDrive.new.async.perform(@guest)
      if @guest.completed?
        redirect_to "/success"
        GuestMailer.rsvp_confirmation(@guest).deliver_now
      else
        redirect_to "/error"
      end
    else
      Guest.update(params[:guests].keys, params[:guests].values)
      UpdateDrive.new.async.perform(@guestorig)
      params[:guests].keys.each do |id|
        @guest = Guest.find(id.to_i)
        UpdateDrive.new.async.perform(@guest)
      end
      @guestorig.update_attributes(guest_params)
      if @guestorig.completed?
        redirect_to "/success"
        GuestMailer.rsvp_confirmation(@guestorig).deliver_now
      else
        redirect_to "/error"
      end
    end

  end

  def create
    @guest = Guest.new(guest_params)

    respond_to do |format|
      if @guest.save
        format.html { redirect_to @guest, notice: 'Guest was successfully created.' }
        format.json { render :show, status: :created, location: @guest }
      else
        format.html { render :new }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guests/1
  # DELETE /guests/1.json
  def destroy
    @guest.destroy
    respond_to do |format|
      format.html { redirect_to guests_url, notice: 'Guest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def update_all
    params['guest'].keys.each do |id|
      @guest = Guest.find(id.to_i)
      @guest.update_attributes(guest_params(id))
    end
    redirect_to(guests_url)
  end

  def edit_all
    @guests = Guest.all
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_guest
    if params[:search]
      name = params[:search]
      @guest = Guest.find_by('lower(name) LIKE lower(?)',  "%#{name}%")
    else
      @guest = Guest.find(params[:id])
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def guest_params
    params.require(:guest).permit(:name, :attending, :notes, :plusone, :plusone_attending, :plusone_notes, :completed, :email)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout false
 
  def new
  end
 
  def create
    @auth = request.env['omniauth.auth']['credentials']
    Token.create(
      access_token: @auth['token'],
      refresh_token: @auth['refresh_token'],
      expires_at: Time.at(@auth['expires_at']).to_datetime)  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/guests/_form.html.erb
<div class="field">
  <div class="attending">
    <%= label :name, "Name", :class => 'name-label' %>
    <%= text_field :name,  :name => 'name' %>
  </div>
  <br>
  <br>
    <%= label :plusone, "Do they get a plusone?", :class => 'plusone-label' %>
 	 <%=  check_box :plusone, :class => 'checkbox'%>
</div>

<div class="field">
    
   <%=  label :household_id, "household id", :class => 'hhid-label' %>
    <%=  text_field :household_id,  :household_id => 'household id' %>
   </div>
 <%= submit "Submit", class: "btn btn-primary" %>

app/views/guests/_guest.html.erb
<%= render @feed %>

app/views/guests/edit.html.erb
<h1 class="guest_name"><%= @guest.name.upcase %></h1>

<%= form_for @guest do |f| %>
<%= render 'shared/error_messages' %>

<% if @groupcount == 1 %>

<div class="guest_form jumbotron">
  <div class="field">
    <div class="attending">
      <h4>Will you be able to attend?</h4>
      <br>
      <div class="btn-group btn-group-justified" data-toggle="buttons">
        <label class="btn btn-lg btn-success"><%= f.radio_button(:attending, true)%> <span class="glyphicon glyphicon-ok" aria-hidden="true"></span> </label>

        <label class="btn btn-lg btn-danger"> <%= f.radio_button(:attending, false)%> <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> </label>
      </div>
    </div>
    <br>
    <br>
    <%= f.text_area :notes, :class => 'input-lg', :placeholder => 'Allergies/Dietary Restrictions/Special Needs? ' %>
    <%= f.check_box :completed, {:class => 'noshow', :checked => "checked", :type => "hidden"} %>
  </div>

  <br>
  <% if @guest.plusone %>
  <div class="well">
    <div class="field">
      <div class="attending">

        <h4>Will you be bringing a guest?</h4>

        <br>
        <div class="btn-group btn-group-justified" data-toggle="buttons">
          <label class="btn btn-lg btn-success"><%= f.radio_button(:attending, true)%> <span class="glyphicon glyphicon-ok" aria-hidden="true"></span> </label>

          <label class="btn btn-lg btn-danger"> <%= f.radio_button(:attending, false)%> <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> </label>
        </div>
      </div>
      <br>
      <br>
      <%= f.text_area :plusone_notes , :class => 'input-lg', :placeholder => 'Allergies/Dietary Restrictions/Special Needs? ' %>
    </div>

    <% end %>
  </div>

</div>

<% else %>

<div class="guest_form jumbotron">
  <div class="field">
    <div class="attending">
      <h4>Will you be able to attend?</h4>
      <br>
      <div class="btn-group btn-group-justified" data-toggle="buttons">
        <label class="btn btn-lg btn-success"><%= f.radio_button(:attending, true)%> <span class="glyphicon glyphicon-ok" aria-hidden="true"></span> </label>

        <label class="btn btn-lg btn-danger"> <%= f.radio_button(:attending, false)%> <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> </label>
      </div>
    </div>
    <br>
    <br>
    <%= f.text_area :notes, :class => 'input-lg', :placeholder => 'Allergies/Dietary Restrictions/Special Needs? ' %>
    <%= f.check_box :completed, {:class => 'noshow', :checked => "checked", :type => "hidden"} %>
  </div>

  <br>
  <% if @guest.plusone %>
  <div class="well">
    <div class="field">
      <div class="attending">

        <h4>Will you be bringing a guest?</h4>

        <br>
        <div class="btn-group btn-group-justified" data-toggle="buttons">
          <label class="btn btn-lg btn-success"><%= f.radio_button(:plusone_attending, true)%> <span class="glyphicon glyphicon-ok" aria-hidden="true"></span> </label>

          <label class="btn btn-lg btn-danger"> <%= f.radio_button(:plusone_attending, false)%> <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> </label>
        </div>
      </div>
      <br>
      <br>
      <%= f.text_area :plusone_notes , :class => 'input-lg', :placeholder => 'Allergies/Dietary Restrictions/Special Needs? ' %>
    </div>

    <% end %>
  </div>

</div>
<div>
  <h1 class="guest_name">OTHERS ON YOUR INVITATION:</h1>
</div>
<div id="household"">
<% for guest in @guests %>
<div class="guest_form panel panel-default">
<%= fields_for "guests[]", guest do |x|%>
<div class="panel-heading">
<h3 class="guest_name"><%= guest.name %></h3>
</div>
<div class="panel-body">
<div class="field">
<div class="attending">
<h4>Will <%= guest.name %> be able to attend?</h4>
<br>
<div class="btn-group btn-group-justified" data-toggle="buttons">
<label class="btn btn-lg btn-success"><%= x.radio_button(:attending, true)%> <span class="glyphicon glyphicon-ok" aria-hidden="true"></span> </label>

<label class="btn btn-lg btn-danger"> <%= x.radio_button(:attending, false)%> <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> </label>
</div>
</div>
<br>
<br>
<%= x.text_area :notes, :class => 'input-lg', :placeholder => 'Allergies/Dietary Restrictions/Special Needs? ' %>
<%= x.check_box :completed, {:class => 'noshow', :checked => "checked", :type => "hidden"} %>
</div>

<% if guest.plusone %>
<div class="well">
<div class="field">
<div class="attending">

<h4>Will they be bringing a guest?</h4>

<br>
<div class="btn-group btn-group-justified" data-toggle="buttons">
<label class="btn btn-lg btn-success"><%= x.radio_button(:plusone_attending, true)%> <span class="glyphicon glyphicon-ok" aria-hidden="true"></span> </label>

<label class="btn btn-lg btn-danger"> <%= x.radio_button(:plusone_attending, false)%> <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> </label>
</div></div>
<br>
<br>
<%= x.text_area :plusone_notes , :class => 'input-lg', :placeholder => 'Allergies/Dietary Restrictions/Special Needs? ' %>
</div>
</div>
<% end %>

</div>
<% end %>
</div>

<% end %>
</div>

<% end %>

<div class="submit">
  <%= f.label :email, "Your email for confirmation" %>
  <br>
  <%= f.text_field :email , :class => 'input-lg', :required => true, :pattern => '[^@]+@[^@]+\.[a-zA-Z]{2,6}' %>
  <%= f.submit "Submit my RSVP", class: "btn btn-primary", :id => 'formsubmit' %>
</div>

<% end %>

app/views/guests/edit_guests.html.erb
<% title "Edit Products" %>  
  
<% form_tag update_guests_products_path :method => :put do %>  
  <% for product in @guests %>  
    <% fields_for "guests[]", guest do |f| %>  
      <h2><%= h guest.name %></h2>  
    <% end %>  
  <% end %>  
  <p><%= submit_tag "Submit" %></p>  
<% end %>  

app/views/guests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Guests</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Attending</th>
      <th>Notes</th>
      <th>Plusone</th>
      <th>Plusone attending</th>
      <th>Plusone notes</th>
      <th>Email</th>
      <th>Completed</th>
      <th>HHID</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @guests.each do |guest| %>
      <tr>
        <td><%= guest.name %></td>
        <td><%= guest.attending %></td>
        <td><%= guest.notes %></td>
        <td><%= guest.plusone %></td>
        <td><%= guest.plusone_attending %></td>
        <td><%= guest.plusone_notes %></td>
        <td><%= guest.email %></td>
        <td><%= guest.completed %></td>
        <td><%= guest.household_id %></td>        
        <td><%= link_to 'Show', guest %></td>
        <td><%= link_to 'Edit', edit_guest_path(guest) %></td>
        <td><%= link_to 'Destroy', guest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Guest', new_guest_path %>

app/views/guests/new.html.erb
<h1>New Guest</h1>

<%= render 'form' %>

<%= link_to 'Back', guests_path %>

app/views/guests/search.html.erb
  <div class="container">
	<h2 class="rsvph2">FIND YOUR RSVP</h2>
<%= form_for(@search, :url => { :action => "edit" }, :html => {:method => :get} ) do |f| %>
	
	  <%= text_field :search, params[:search], nil, placeholder: "Search for your name here...", autocomplete: :off%>
    <% end %>
  </div>

app/views/guests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @guest.name %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @guest.completed %>
</p>

<p>
  <strong>Attending:</strong>
  <%= @guest.attending %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @guest.notes %>
</p>

<p>
  <strong>Plusone:</strong>
  <%= @guest.plusone %>
</p>

<p>
  <strong>Plusone attending:</strong>
  <%= @guest.plusone_attending %>
</p>

<p>
  <strong>Plusone notes:</strong>
  <%= @guest.plusone_notes %>
</p>

<p>
  <strong>Household:</strong>
  <%= @guest.household_id %>
</p>

<p>
  <strong>Email:</strong>
  <%= @guest.email %>
</p>

<%= link_to 'Edit', edit_guest_path(@guest) %> |
<%= link_to 'Back', guests_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Brooke + Matt | RSVP</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:800,400|Lato|Open+Sans+Condensed:700|Yanone+Kaffeesatz' rel='stylesheet' type='text/css'>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <%= csrf_meta_tags %>
  </head>
  <body>
    <% flash.each do |message_type, message| %>
    <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <%end%>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>

  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @guest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@guest.errors.count, "error") %> prohibited this guest from being saved:</h2>

      <ul>
      <% @guest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

app/views/static_pages/already_completed.html.erb
<div id="failure">
  <div class="failure">
    <h1 class="guest_name">HOLD UP!</h1>
  </div>
  </div>
  <p class="thank_you">
    It looks like you may have already RSVP'd!  If you need to update anything, please feel free to email us at:
    <div class="thank_you_sm">
      <div class="well">
        <a href="mailto:pazoleswedding+RSVP@gmail.com">PazolesWedding@gmail.com</a>
      </div>
    </div>
  </p>

  <section class="thank_you">
    <nav class="cl-effect"id="cl-effect">
      <a href="http://www.brookeplusmatt.com">BACK TO THE HOME PAGE</a>
    </nav>
  </section>

app/views/static_pages/error.html.erb
<div id="failure">
  <div class="failure">
    <h1 class="guest_name">UH OH</h1>
  </div>
  </div>
  <p class="thank_you">
    Looks like there was an error.  To RSVP, please email us at:
    <div class="thank_you">
      <div class="well">
        <a href="mailto:pazoleswedding+RSVP@gmail.com">PazolesWedding@gmail.com</a>
      </div>
    </div>
  </p>

  <section class="thank_you">
    <nav class="cl-effect"id="cl-effect">
      <a href="http://www.brookeplusmatt.com">BACK TO THE HOME PAGE</a>
    </nav>
  </section>

app/views/static_pages/index.html.erb
  <div class="container">
	<h2 class="rsvph2">FIND YOUR INVITATION</h2>
	<%= form_tag url_for(:controller => 'guests', :action => 'edit', :id => 'search'), :method => 'get' do %>

	
	  <%= text_field_tag "search", nil, placeholder: "Search for your name here...", autocomplete: :off%>
	        <button type="submit" class="btn btn-primary btn-xl">SUBMIT</button>

    <% end %>
  </div>

app/views/static_pages/success.html.erb
<div id="success">
  <div class="success">
    <h1 class="guest_name">SUCCESS!</h1>
  </div>
  </div>
  <p class="thank_you">
    If you need to update anything, please feel free to email us at:
    <div class="thank_you_sm">
      <div class="well">
        <a href="mailto:pazoleswedding+RSVP@gmail.com">PazolesWedding@gmail.com</a>
      </div>
    </div>
  </p>

  <section class="thank_you">
    <nav class="cl-effect"id="cl-effect">
      <a href="http://www.brookeplusmatt.com">BACK TO THE HOME PAGE</a>
    </nav>
  </section>